
import { LevelTheme, Language, Relic, AltarEffect, ItemEntity, NPCType } from './types';

export const MAP_WIDTH = 100;
export const MAP_HEIGHT = 60;
export const MAX_LEVELS = 150;
export const SAVE_VERSION = 'v1.8.0'; 

export const INITIAL_PLAYER_STATS = {
  hp: 120,
  maxHp: 120,
  attack: 12,
  armor: 8,
  maxArmor: 8,
  speed: 12,
};

export const BIOME_MUSIC_URLS: Record<LevelTheme | 'BOSS', string> = {
  VOID: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/abismo.mp3',
  CATACOMBS: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/catacumbas_alagadas.mp3',
  CAVE: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/cavernas.mp3',
  HIVE: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/comeia_profunda.mp3',
  MECHANICAL: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/complexo_mecanico.mp3',
  DESERT: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/dunas.mp3',
  FOREST: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/floresta.mp3',
  FURNACE: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/fornalha_abissal.mp3',
  MATRIX: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/matrix.mp3',
  OSSUARY: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/ossuario.mp3',
  SWAMP: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/pantano_toxico.mp3',
  SNOW: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/picos_de_gelo.mp3',
  ASTRAL: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/plano_astral.mp3',
  RUINS: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/ruinas_antigas.mp3',
  TEMPLE: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/templo_esquecido.mp3',
  CORRUPTED: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/zona_corrompida.mp3',
  CHAOS: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/zona_do_caos.mp3',
  INFERNO: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/zona_infernal.mp3',
  BOSS: 'https://pub-2a8e52d1971240ee8051b19ae39b05ff.r2.dev/boss_final.mp3'
};

export const POISONOUS_ENEMIES = [
  'Aranha Cavernosa', 'Escorpião Gigante', 'Verme da Areia', 'Serpente Aquática', 
  'Bruxa da Floresta', 'Mutante Corrompido', 'Lodo Venenoso', 'Aberração Putrefata', 'Sanguessuga Gigante'
];

export const RELICS_POOL: Relic[] = [
  { id: 'slots', name: 'relic_slots_name', description: 'relic_slots_desc', icon: 'Backpack' },
  { id: 'bleed', name: 'relic_bleed_name', description: 'relic_bleed_desc', icon: 'Droplets' },
  { id: 'defense', name: 'relic_defense_name', description: 'relic_defense_desc', icon: 'ShieldAlert' },
  { id: 'crit', name: 'relic_crit_name', description: 'relic_crit_desc', icon: 'Eye' },
  { id: 'power', name: 'relic_power_name', description: 'relic_power_desc', icon: 'Zap' },
  { id: 'vamp', name: 'relic_vamp_name', description: 'relic_vamp_desc', icon: 'Hourglass' },
  { id: 'alch', name: 'relic_alch_name', description: 'relic_alch_desc', icon: 'FlaskConical' },
  { id: 'save', name: 'relic_save_name', description: 'relic_save_desc', icon: 'RefreshCcw' },
  { id: 'memory', name: 'relic_memory_name', description: 'relic_memory_desc', icon: 'Brain' },
  { id: 'gaze', name: 'relic_gaze_name', description: 'relic_gaze_desc', icon: 'Sparkles' },
  { id: 'collar', name: 'relic_collar_name', description: 'relic_collar_desc', icon: 'Skull' },
  { id: 'bag', name: 'relic_bag_name', description: 'relic_bag_desc', icon: 'Coins' },
  { id: 'coin', name: 'relic_coin_name', description: 'relic_coin_desc', icon: 'CircleDollarSign' },
  { id: 'heart', name: 'relic_heart_name', description: 'relic_heart_desc', icon: 'HeartOff' },
  { id: 'mark', name: 'relic_mark_name', description: 'relic_mark_desc', icon: 'Flame' },
  { id: 'echo', name: 'relic_echo_name', description: 'relic_echo_desc', icon: 'Ghost' },
];

export const BLESSINGS_POOL: AltarEffect[] = [
  { id: 'sharp_blood', type: 'BLESSING', nameKey: 'b_sharp_name', descKey: 'b_sharp_desc' },
  { id: 'contained_fury', type: 'BLESSING', nameKey: 'b_fury_name', descKey: 'b_fury_desc' },
  { id: 'anxious_strike', type: 'BLESSING', nameKey: 'b_strike_name', descKey: 'b_strike_desc' },
  { id: 'consecrated_fists', type: 'BLESSING', nameKey: 'b_fists_name', descKey: 'b_fists_desc' },
  { id: 'open_eyes', type: 'BLESSING', nameKey: 'b_eyes_name', descKey: 'b_eyes_desc' },
  { id: 'pilgrim_luck', type: 'BLESSING', nameKey: 'b_luck_name', descKey: 'b_luck_desc' },
  { id: 'surrendered_blood', type: 'BLESSING', nameKey: 'b_surrendered_name', descKey: 'b_surrendered_desc' },
  { id: 'accepted_offering', type: 'BLESSING', nameKey: 'b_accepted_name', descKey: 'b_accepted_desc' },
  { id: 'sacred_greed', type: 'BLESSING', nameKey: 'b_greed_name', descKey: 'b_greed_desc' },
  { id: 'merchant_blessing', type: 'BLESSING', nameKey: 'b_merchant_name', descKey: 'b_merchant_desc' },
  { id: 'consecrated_chest', type: 'BLESSING', nameKey: 'b_chest_name', descKey: 'b_chest_desc' },
];

export const CURSES_POOL: AltarEffect[] = [
  { id: 'fragile_blood', type: 'CURSE', nameKey: 'c_fragile_name', descKey: 'c_fragile_desc' },
  { id: 'trembling_hands', type: 'CURSE', nameKey: 'c_hands_name', descKey: 'c_hands_desc' },
  { id: 'short_breath', type: 'CURSE', nameKey: 'c_breath_name', descKey: 'c_breath_desc' },
  { id: 'mark_of_prey', type: 'CURSE', nameKey: 'c_mark_name', descKey: 'c_mark_desc' },
  { id: 'slow_reflexes', type: 'CURSE', nameKey: 'c_reflexes_name', descKey: 'c_reflexes_desc' },
  { id: 'ritual_darkness', type: 'CURSE', nameKey: 'c_darkness_name', descKey: 'c_darkness_desc' },
  { id: 'profane_thirst', type: 'CURSE', nameKey: 'c_thirst_name', descKey: 'c_thirst_desc' },
  { id: 'denied_offering', type: 'CURSE', nameKey: 'c_denied_name', descKey: 'c_denied_desc' },
  { id: 'cursed_greed', type: 'CURSE', nameKey: 'c_greed_name', descKey: 'c_greed_desc' },
  { id: 'less_weight', type: 'CURSE', nameKey: 'c_weight_name', descKey: 'c_weight_desc' },
  { id: 'blood_tribute', type: 'CURSE', nameKey: 'c_tribute_name', descKey: 'c_tribute_desc' },
];

export const BIOME_ENEMIES: Record<LevelTheme, string[]> = {
  CAVE: ['Morcego Gigante', 'Aranha Cavernosa', 'Goblin', 'Verme de Pedra', 'Troll'],
  SNOW: ['Lobo de Gelo', 'Elemental Congelado', 'Guerreiro Nórdico Espectral', 'Golem de Gelo', 'Espírito da Nevassa'],
  DESERT: ['Escorpião Gigante', 'Verme da Areia', 'Bandido do Deserto', 'Esqueleto Soterrado', 'Djinn Corrompido'],
  FOREST: ['Lobo Selvagem', 'Ent Corrompido', 'Arqueiro Espectral', 'Besta da Mata', 'Bruxa da Floresta'],
  INFERNO: ['Demônio Menor', 'Ímpio Flamejante', 'Cavaleiro Infernal', 'Cão do Inferno', 'Sacerdote Demoníaco'],
  RUINS: ['Guardião de Pedra', 'Esqueleto Ancestral', 'Autômato Antigo', 'Cultista Esquecido', 'Espírito das Ruínas'],
  VOID: ['Criatura Sombria', 'Aberração sem Forma', 'Sombra Viva', 'Observador do Vazio', 'Entidade Faminta'],
  MECHANICAL: ['Autômato de Combate', 'Drone Defeituoso', 'Torre Mecânica', 'Engrenagem Viva', 'Sentinela de Aço'],
  CORRUPTED: ['Mutante Corrompido', 'Besta Deformada', 'Humano Possuído', 'Parasita Gigante', 'Massa Orgânica Hostil'],
  CATACOMBS: ['Zumbi Encharcado', 'Criatura Anfíbia', 'Serpente Aquática', 'Espírito Afogado', 'Slime Aquático'],
  OSSUARY: ['Esqueleto Armado', 'Necromante', 'Guardião de Ossos', 'Espírito Funerário', 'Colosso Ósseo'],
  ASTRAL: ['Entidade Etérea', 'Guardião Astral', 'Fragmento de Consciência', 'Eco Vivo', 'Seres Translúcidos'],
  MATRIX: ['Programa Corrompido', 'Agente de Segurança', 'Vírus Consciente', 'Avatar Hostil', 'Entidade Digital'],
  FURNACE: ['Íncubo de Cinzas', 'Larva Ígnea', 'Guardião da Brasa', 'Súcubo Incandescente', 'Elemental de Fogo Instável', 'Colosso Vulcânico'],
  SWAMP: ['Lodo Venenoso', 'Sanguessuga Gigante', 'Morcego Doente', 'Xamã do Brejo', 'Crocodilo Mutante', 'Aberração Putrefata'],
  TEMPLE: ['Estátua Animada', 'Sentinela Antiga', 'Sacerdote Profanado', 'Autômato Rúnico', 'Guardião de Obelisco', 'Avatar do Templo'],
  CHAOS: ['Entidade Fraturada', 'Eco Distorcido', 'Parasita do Caos', 'Aberração Mutável', 'Vulto Caótico', 'Núcleo Anômalo'],
  HIVE: ['Larva Rasteira', 'Operária da Colmeia', 'Soldado Quitinoso', 'Aranha Tecelã', 'Rainha Menor', 'Matriz da Colmeia'],
};

export const THEME_CONFIG: Record<LevelTheme, { nameKey: string, wall: string, floor: string, char: string, wallChar: string }> = {
  CAVE: { nameKey: 'theme_cave', wall: 'text-zinc-600', floor: 'text-zinc-900', char: '°', wallChar: '▓' },
  SNOW: { nameKey: 'theme_snow', wall: 'text-cyan-100', floor: 'text-blue-900', char: '·', wallChar: '❄' },
  DESERT: { nameKey: 'theme_desert', wall: 'text-orange-700', floor: 'text-yellow-900', char: '≈', wallChar: '▒' },
  FOREST: { nameKey: 'theme_forest', wall: 'text-green-800', floor: 'text-green-950', char: '♣', wallChar: 'T' },
  INFERNO: { nameKey: 'theme_inferno', wall: 'text-red-600', floor: 'text-red-950', char: '″', wallChar: '▲' },
  RUINS: { nameKey: 'theme_ruins', wall: 'text-amber-800', floor: 'text-stone-900', char: '☖', wallChar: '🧱' },
  VOID: { nameKey: 'theme_void', wall: 'text-purple-900', floor: 'text-black', char: ' ', wallChar: '?' },
  MECHANICAL: { nameKey: 'theme_mechanical', wall: 'text-zinc-400', floor: 'text-zinc-800', char: '⚙', wallChar: '█' },
  CORRUPTED: { nameKey: 'theme_corrupted', wall: 'text-fuchsia-900', floor: 'text-purple-950', char: '☣', wallChar: '✕' },
  CATACOMBS: { nameKey: 'theme_catacombs', wall: 'text-slate-700', floor: 'text-slate-900', char: '♒', wallChar: '⛩' },
  OSSUARY: { nameKey: 'theme_ossuary', wall: 'text-zinc-200', floor: 'text-zinc-700', char: '☠', wallChar: '✟' },
  ASTRAL: { nameKey: 'theme_astral', wall: 'text-sky-400', floor: 'text-sky-950', char: '✨', wallChar: '✧' },
  MATRIX: { nameKey: 'theme_matrix', wall: 'text-emerald-500', floor: 'text-black', char: '1', wallChar: '0' },
  FURNACE: { nameKey: 'theme_furnace', wall: 'text-orange-600', floor: 'text-red-950', char: '~', wallChar: '♨' },
  SWAMP: { nameKey: 'theme_swamp', wall: 'text-emerald-700', floor: 'text-green-950', char: '≈', wallChar: '⍾' },
  TEMPLE: { nameKey: 'theme_temple', wall: 'text-amber-500', floor: 'text-stone-900', char: '∏', wallChar: '🏛' },
  CHAOS: { nameKey: 'theme_chaos', wall: 'text-fuchsia-600', floor: 'text-purple-950', char: '?', wallChar: '🌀' },
  HIVE: { nameKey: 'theme_hive', wall: 'text-yellow-700', floor: 'text-orange-950', char: '⬡', wallChar: '🕸' },
};

export const TILE_COLORS: Record<string, string> = {
  WALL: 'text-zinc-700',
  FLOOR: 'text-zinc-900',
  PLAYER: 'text-yellow-400',
  ENEMY: 'text-red-500',
  CHEST: 'text-blue-400',
  STAIRS: 'text-green-500',
  KEY: 'text-yellow-500',
  POTION: 'text-pink-400',
  ITEM: 'text-purple-400',
  MERCHANT: 'text-indigo-400',
  ALTAR: 'text-purple-500',
  TRON: 'text-cyan-400',
  PET: 'text-orange-400',
  TRAP: 'text-zinc-500',
  EGG: 'text-white'
};

export const NPC_COLORS: Record<NPCType, string> = {
  MERCHANT_WOUNDED: 'text-zinc-400',
  PRISONER: 'text-orange-700',
  ALCHEMIST: 'text-teal-600',
  IDOL: 'text-stone-500',
  KNIGHT: 'text-blue-700',
  CHILD: 'text-cyan-300',
  CARTOGRAPHER: 'text-orange-800',
  VOICE: 'text-fuchsia-800',
  GUARD: 'text-rose-900'
};

export const ITEM_POOL: Omit<ItemEntity, 'x' | 'y' | 'id'>[] = [
  { name: 'item_sword_1', stat: 'attack', value: 5, iconType: 'sword', price: 60, tier: 1 },
  { name: 'item_sword_2', stat: 'attack', value: 10, iconType: 'sword', price: 120, tier: 2 },
  { name: 'item_sword_3', stat: 'attack', value: 15, iconType: 'sword', price: 180, tier: 3 },
  { name: 'item_sword_4', stat: 'attack', value: 20, iconType: 'sword', price: 240, tier: 4 },
  { name: 'item_sword_5', stat: 'attack', value: 25, iconType: 'sword', price: 300, tier: 5 },
  { name: 'item_shield_1', stat: 'maxArmor', value: 5, iconType: 'shield', price: 50, tier: 1 },
  { name: 'item_shield_2', stat: 'maxArmor', value: 10, iconType: 'shield', price: 100, tier: 2 },
  { name: 'item_shield_3', stat: 'maxArmor', value: 15, iconType: 'shield', price: 150, tier: 3 },
  { name: 'item_shield_4', stat: 'maxArmor', value: 20, iconType: 'shield', price: 200, tier: 4 },
  { name: 'item_shield_5', stat: 'maxArmor', value: 25, iconType: 'shield', price: 250, tier: 5 },
  { name: 'item_health_1', stat: 'maxHp', value: 10, iconType: 'heart', price: 150, tier: 1 },
  { name: 'item_health_2', stat: 'maxHp', value: 20, iconType: 'heart', price: 300, tier: 2 },
  { name: 'item_health_3', stat: 'maxHp', value: 30, iconType: 'heart', price: 450, tier: 3 },
  { name: 'item_health_4', stat: 'maxHp', value: 40, iconType: 'heart', price: 600, tier: 4 },
  { name: 'item_health_5', stat: 'maxHp', value: 50, iconType: 'heart', price: 750, tier: 5 },
  { name: 'item_speed_1', stat: 'speed', value: 5, iconType: 'zap', price: 80, tier: 1 },
  { name: 'item_speed_2', stat: 'speed', value: 10, iconType: 'zap', price: 160, tier: 2 },
  { name: 'item_speed_3', stat: 'speed', value: 15, iconType: 'zap', price: 240, tier: 3 },
  { name: 'item_speed_4', stat: 'speed', value: 20, iconType: 'zap', price: 320, tier: 4 },
  { name: 'item_speed_5', stat: 'speed', value: 25, iconType: 'zap', price: 400, tier: 5 },
];

export const TRANSLATIONS: Record<Language, any> = {
  PT: {
    // NPCs REWRITTEN
    npc_merchant_wounded_name: "Mercador Ferido", 
    npc_merchant_wounded_desc: "Um mercador ferido se arrasta contra a parede. Sua mochila aberta revela moedas manchadas de sangue. Ele ergue os olhos e espera sua decisão.", 
    npc_merchant_wounded_c1: "Dar uma Poção", 
    npc_merchant_wounded_c2: "Dar 50 Ouro", 
    npc_merchant_wounded_c3: "Ignorar", 
    npc_merchant_wounded_c4: "Roubar",
    
    npc_prisoner_name: "Prisioneira das Catacumbas", 
    npc_prisoner_desc: "Correntes enferrujadas prendem uma mulher exausta. O chão treme levemente. Você sente que sua decisão terá peso.", 
    npc_prisoner_c1: "Libertar", 
    npc_prisoner_c2: "Matar", 
    npc_prisoner_c3: "Ignorar",
    
    npc_alchemist_name: "Alquimista Obcecado", 
    npc_alchemist_desc: "Frascos quebrados, vapores tóxicos e olhos enlouquecidos. Ele precisa de um antídoto para concluir algo que talvez nunca devesse existir.", 
    npc_alchemist_c1: "Entregar Antídoto", 
    npc_alchemist_c2: "Recusar", 
    npc_alchemist_c3: "Exigir Pagamento",
    
    npc_idol_name: "Ídolo Sussurrante", 
    npc_idol_desc: "A estátua pulsa levemente. Sussurros ecoam direto na sua mente, exigindo uma oferta.", 
    npc_idol_c1: "Oferecer Ouro (100)", 
    npc_idol_c2: "Oferecer Vida (10%)", 
    npc_idol_c3: "Destruir o Ídolo",
    
    npc_knight_name: "Cavaleiro Sem Rosto", 
    npc_knight_desc: "Um cavaleiro sem rosto segura uma espada quebrada. Sua voz ecoa oca dentro da armadura.", 
    npc_knight_c1: "Aceitar Missão (Matar 3)", 
    npc_knight_c2: "Recusar", 
    npc_knight_c3: "Atacar",
    
    npc_child_name: "Criança Perdida", 
    npc_child_desc: "Uma criança assustada chora entre sombras. O caminho à frente está repleto de monstros.", 
    npc_child_c1: "Ajudar (Bênção)", 
    npc_child_c2: "Ignorar", 
    npc_child_c3: "Investigar",
    
    npc_cartographer_name: "Velho Cartógrafo", 
    npc_cartographer_desc: "Mapas rabiscados cobrem o chão. Ele não vende itens, apenas verdades inconvenientes.", 
    npc_cartographer_c1: "Comprar Verdade (80)", 
    npc_cartographer_c2: "Ameaçar", 
    npc_cartographer_c3: "Ignorar",
    
    npc_voice_name: "Voz na Escuridão", 
    npc_voice_desc: "Você ouve uma voz sem forma. Ela pede... algo. Talvez atenção. Talvez um preço.", 
    npc_voice_c1: "Responder", 
    npc_voice_c2: "Oferecer Ouro (50)", 
    npc_voice_c3: "Silêncio",
    
    npc_guard_name: "Guarda Corrompido", 
    npc_guard_desc: "Um antigo protetor, agora deformado. Ele pede redenção com os últimos traços de sanidade.", 
    npc_guard_c1: "Dar Antídoto", 
    npc_guard_c2: "Matar", 
    npc_guard_c3: "Ignorar",

    // FEEDBACK TITLES & STRINGS
    fb_charity: "Ato de Caridade",
    fb_greed: "Avareza",
    fb_cruelty: "Crueldade",
    fb_ignorance: "Indiferença",
    fb_deal: "Trato Feito",
    fb_quest: "Missão Aceita",
    fb_consequence: "Consequência",
    fb_blessing: "Bênção Recebida",
    fb_curse: "Maldição",
    fb_combat: "Combate Iminente",
    fb_theft: "Roubo",
    
    // FEEDBACK SPECIFIC
    fb_desc_merchant_help: "O mercador agradece com lágrimas. Ele promete descontos futuros.",
    fb_desc_merchant_theft: "Você rouba o que pode. O mercador pragueja contra sua alma.",
    fb_desc_prisoner_free: "Ela se levanta, jurando lutar ao seu lado por um tempo.",
    fb_desc_alchemist_help: "Ele ri maniacamente e lhe entrega uma mistura instável.",
    fb_desc_idol_gold: "O ídolo consome o ouro e brilha com poder.",
    fb_desc_idol_blood: "O ídolo drena seu sangue, mas te fortalece.",
    fb_desc_knight_quest: "O cavaleiro aponta sua espada para o escuro. A caçada começou.",
    fb_desc_child_help: "A criança toca sua mão. Uma luz quente te envolve.",
    fb_desc_cartographer: "Ele revela os segredos deste andar.",
    fb_desc_voice_response: "A voz sussurra segredos antigos.",
    fb_desc_guard_help: "Sua pele volta ao normal. Ele lhe entrega seu escudo.",

    // EFFECTS
    eff_merchant_discount: "Desconto no Mercador (-50%)",
    eff_merchant_tax: "Imposto do Mercador (+50%)",
    eff_prisoner_join: "Prisioneira aliada (10 níveis)",
    eff_more_enemies: "Mais inimigos aparecerão",
    eff_quest_start: "Derrote 3 Inimigos",
    eff_map_reveal: "Mapa Revelado",
    eff_traps_reveal: "Armadilhas Reveladas",
    
    // ... (Tutorial keys unchanged)
    tut_prove_title: "PROVE SEU VALOR", tut_prove_desc: "Antes de avançar, você precisa provar seu valor.\nDerrote pelo menos um inimigo para seguir adiante.",
    // ... (Keeping all existing translations)
    tut_key_title: "ENCONTRE A CHAVE", tut_key_desc: "A saída está trancada.\nExplore o mapa até encontrar a chave.",
    tut_stairs_title: "USE A ESCADA", tut_stairs_desc: "Com a chave em mãos, procure a escada.\nEla leva você a níveis mais profundos.",
    tut_battle_title: "COMO FUNCIONAM AS BATALHAS", tut_battle_desc: "As batalhas são automáticas.\nVocê e o inimigo atacam em turnos.",
    tut_attr_title: "ATRIBUTOS DO PERSONAGEM", 
    tut_attr_hp: "Se a vida chegar a 0, a run termina.",
    tut_attr_atk: "Define quanto dano você causa por turno.",
    tut_attr_def: "Absorve o dano antes da vida. Se recupera entre batalhas.",
    tut_attr_spd: "Determina quem ataca primeiro.",
    tut_init_title: "INICIATIVA IMPORTA", tut_init_desc: "Atacar primeiro pode decidir a batalha.\nVelocidade salva vidas.",
    tut_merchant_title: "O MERCADOR", tut_merchant_desc: "Você pode encontrar um mercador durante a exploração.\nEle vende melhorias diretas para seus atributos.",
    tut_choice_title: "ESCOLHAS IMPORTAM", tut_choice_desc: "Nem todo caminho é seguro.\nNem toda decisão traz recompensa.",
    tut_end_title: "ENCERRAMENTO", tut_end_desc: "O mundo não espera por heróis.\nApenas os persistentes descem mais fundo.",

    inventory_title: "INVENTÁRIO", inventory_full_title: "Inventário Cheio!", inventory_full_btn: "OK", inventory_full: "Inventário cheio!",
    use: "USAR", store: "GUARDAR", close: "FECHAR", exit: "SAIR", next: "PRÓXIMO", start: "COMEÇAR", back: "VOLTAR", yes: "SIM", no: "NÃO", vs: "VS",
    turn_log_title: "Log de Turnos", save_reset_title: "ATUALIZAÇÃO DO ABISMO", save_reset_desc: "Os ventos mudaram. Sua jornada anterior foi perdida nas sombras de uma atualização, mas o caminho se abre novamente.", save_reset_btn: "ACEITAR O DESTINO",
    descending: "Descendo", relic_choice: "ESCOLHA UMA RELÍQUIA", relic_active: "RELÍQUIA ATIVA", hero_placeholder: "NOME DO HERÓI", continue_journey: "Continuar Jornada",
    new_game: "Novo Jogo", start_journey: "Iniciar Jornada", feedback: "Feedback", real_shop: "Loja",
    shop_title: "LOJA DE APOIO", shop_crow_title: "Desbloquear Corvo", shop_crow_desc: "Mascote permanente. Detecta armadilhas. (Item Permanente)", shop_coffee_title: "Apoiar o Dev",
    shop_coffee_desc: "Compre um café para quem criou o jogo!", shop_buy_btn: "ADQUIRIR", unlock_success_title: "RECOMPENSA OBTIDA!", unlock_success_desc: "Obrigado pelo seu apoio! O item foi adicionado permanentemente à sua conta.",
    level: "Nível", hp: "VIDA", armor: "ESCUDO", atk: "ATK", vel: "VEL", diary: "Diario", view_diary: "Ver Diário", hide_diary: "Ocultar Diário", death_title: "MORTE", death_desc: "O Abismo reivindicou sua alma.",
    rebirth: "Renascer", victory: "Vitória", collect_reward: "COLETAR RECOMPENSA", succumb: "SUCUMBIR AO ABISMO", chest_title: "Bênção do Baú", merchant_title: "Mercador Errante", altar_title: "Altar das Sombras",
    altar_inactive: "O Altar permanece silente. Mate um inimigo primeiro.", altar_prompt: "Prostre-se diante do Altar e aceite seu destino.", altar_button: "ORAR", close_deal: "Fechar Negócio", bought_pet: "Mascote comprado!",
    bought_potion: "Poção comprada!", bought_item: "Equipado!", tron_active: "CAVALO FANTASMA ATIVADO!", final_stats: "ESTATÍSTICAS FINAIS", blood: "SANGUE", key: "CHAVE", shop_coins: "MOEDAS", no_effect: "NENHUM EFEITO",
    crow_tooltip: "Corvo Vigilante", hero_default: "Herói", share_hero: "Herói", share_level: "Nível Alcançado", share_atk: "Ataque", share_def: "Escudo", share_msg: "Desafie o abismo você também!", share_copied: "Desafio copiado para a área de transferência!",
    shop_ghost_horse: "Cavalo Fantasma (20s)", shop_ghost_desc: "Iniciativa Máxima + Rastro", shop_bag: "Mochila Expandida (+5 Slots)", shop_bag_desc: "Aumenta capacidade do inventário", shop_max: "MÁXIMO ATINGIDO", shop_attribute: "Atributo",
    potion_found: "Frasco Encontrado", potion_desc: "Recupera", potion_desc_suffix: "% da vida", stat_attack: "Ataque", stat_armor: "Armadura", stat_speed: "Velocidade",
    log_trampled: "ATROPELADO!", log_explode: "explodiu!", log_recover_breath: "Você recupera o fôlego...", log_miss: "Você errou o ataque!", log_anxious: "GOLPE ANSIOSO!", log_crit: "CRÍTICO!", log_absorbed: "absorveu",
    log_drain: "drenou", log_bleed: "Você está sangrando!", log_paralyzed: "PARALISADO! Perdeu o turno!", log_entered: "entrou no abismo.", log_descending: "Descendo para o nível", log_key: "Chave coletada!", log_locked: "Trancado. Mate 1 inimigo e pegue a chave!",
    combat_dealt: "causou", combat_damage: "de dano", combat_player: "Você", combat_enemy: "Inimigo", combat_pet: "Mascote", pet_lobo: "LOBO", pet_puma: "PUMA", pet_corvo: "CORVO", pet_cavalo: "CAVALO", pet_urso: "URSO", pet_cachorro: "CACHORRO",
    poisoned: "ENVENENADO", cured: "CURADO DO VENENO!", poison_damage: "Veneno", trap_spike: "Armadilha de Espinhos!", trap_poison: "Armadilha de Veneno!", trap_alarm: "ALARME! INIMIGO ATRAÍDO!", trap_explosive: "KABOOM! EXPLOSÃO!", trap_evaded: "Armadilha evitada (Velocidade)!",
    crow_reveal: "O Corvo avistou armadilhas!",
    level_complete: "NÍVEL CONCLUÍDO", next_level_desc: "A escuridão te abraça enquanto você desce...", descend_btn: "DESCER MAIS FUNDO",
    
    // RESTORED KEYS
    theme_cave: "Cavernas Profundas", theme_snow: "Picos Congelados", theme_desert: "Dunas Mortais", theme_forest: "Floresta Negra", theme_inferno: "Zona Infernal", theme_ruins: "Ruinas Antigas",
    theme_void: "Vazio Abissal", theme_mechanical: "Complexo Mecânico", theme_corrupted: "Zona Corrompida", theme_catacombs: "Catacumbas", theme_ossuary: "Ossuário", theme_astral: "Plano Astral",
    theme_matrix: "Matrix", theme_furnace: "Fornalha", theme_swamp: "Pântano", theme_temple: "Templo", theme_chaos: "Caos", theme_hive: "Colmeia",

    relic_slots_name: "+5 Slot Inventário", relic_slots_desc: "Aumenta permanentemente o inventário em 5 slots.",
    relic_bleed_name: "Diente Serrilhado", relic_bleed_desc: "+1% de chance de causar sangramento permanente ao inimigo.",
    relic_defense_name: "Placa Rachada", relic_defense_desc: "Reduz em 1 o dano recebido (mínimo 1).",
    relic_crit_name: "Olho do Caçador", relic_crit_desc: "+1% de chance de crítico.",
    relic_power_name: "Punho Enrijecido", relic_power_desc: "Primeiro ataque em cada andar causa +10% de dano.",
    relic_vamp_name: "Ampulheta Carmesim", relic_vamp_desc: "Recupera 15% de vida ao matar um inimigo.",
    relic_alch_name: "Resíduo Alquímico", relic_alch_desc: "Poções curam +5% a mais.",
    relic_save_name: "Frasco Instável", relic_save_desc: "5% de chance de uma poção não ser consumida ao usar.",
    relic_memory_name: "Memória Destilada", relic_memory_desc: "Primeira poção usada em cada run tem efeito dobrado.",
    relic_gaze_name: "Gaze Antiga", relic_gaze_desc: "Sempre começa a run com 1 poção que cura +70%.",
    relic_collar_name: "Coleira de Ossos", relic_collar_desc: "Pets ganham +10 de dano base.",
    relic_bag_name: "Bolsa Costurada", relic_bag_desc: "+5% de ouro ganho.",
    relic_coin_name: "Moeda Antiga", relic_coin_desc: "5% de chance de inimigos droparem ouro extra.",
    relic_heart_name: "Coração Fissurado", relic_heart_desc: "+10% dano, -5% HP máximo.",
    relic_mark_name: "Marca do Sacrifício", relic_mark_desc: "Começa a run com menos 10% de vida, mas +60 moedas.",
    relic_echo_name: "Eco das Mortes", relic_echo_desc: "Herda 20% de todos os atributos da run anterior.",

    b_sharp_name: "Sangue Afiado", b_sharp_desc: "Após matar 1 inimigo, +10% de dano até sair do nível.",
    b_fury_name: "Fúria Contida", b_fury_desc: "+15% de dano enquanto estiver com menos de 50% de vida.",
    b_strike_name: "Golpe Ansioso", b_strike_desc: "O primeiro ataque em combate causa dano dobrado.",
    b_fists_name: "Punhos Consagrados", b_fists_desc: "Ataques ignoram parte da defesa inimiga.",
    b_eyes_name: "Olhos Abertos", b_eyes_desc: "Revela a posição da chave no mapa.",
    b_luck_name: "Sorte Peregrina", b_luck_desc: "5% de chance de baús darem +100 moedas.",
    b_surrendered_name: "Sangue Rendido", b_surrendered_desc: "Recupera 30% da vida ao matar inimigos.",
    b_accepted_name: "Oferta Aceita", b_accepted_desc: "A primeira poção usada não é consumida.",
    b_greed_name: "Ganância Sagrada", b_greed_desc: "Inimigos dropam +15% de ouro neste andar.",
    b_merchant_name: "Bênção do Mercador", b_merchant_desc: "Itens custam -20% até o próximo nível.",
    b_chest_name: "Baú Consagrado", b_chest_desc: "O próximo baú concede bônus duplicado.",

    c_fragile_name: "Sangue Frágil", c_fragile_desc: "Recebe +10% de dano até sair do andar.",
    c_hands_name: "Mãos Trêmulas", c_hands_desc: "15% de chance de errar ataques.",
    c_breath_name: "Fôlego Curto", c_breath_desc: "Não pode atacar em turnos consecutivos (recupera fôlego).",
    c_mark_name: "Marca da Presa", c_mark_desc: "Inimigos causam sangramento (-2 HP por turno).",
    c_reflexes_name: "Reflexos Lentos", c_reflexes_desc: "Inimigos atacam primeiro.",
    c_darkness_name: "Escuridão Ritual", c_darkness_desc: "Campo de visão reduzido.",
    c_thirst_name: "Sede Profana", c_thirst_desc: "Poções curam -20% menos.",
    c_denied_name: "Oferta Negada", c_denied_desc: "A primeira poção é desperdiçada ao usar.",
    c_greed_name: "Ganância Maldita", c_greed_desc: "Inimigos dropam -25% de ouro.",
    c_weight_name: "Peso Morto", c_weight_desc: "Sua velocidade é reduzida.",
    c_tribute_name: "Tributo de Sangue", c_tribute_desc: "Perde vida ao pegar ouro.",

    follower_prisoner: "Prisioneira", follower_knight: "Caballero",
    no_potion: "Sem poções!", no_gold: "Sem ouro!", no_antidote: "Sem antídoto!",
    
    shop_solo_dev_msg: "Este jogo é desenvolvido e mantido por um desenvolvedor solo, com muito cuidado e dedicação.\nSe você gosta da experiência e deseja apoiar o projeto, pode adquirir qualquer um dos itens abaixo.\nAs compras ajudam diretamente a manter o jogo online, cobrir custos de servidores, ferramentas, atualizações e novas melhorias.\n\nTodos os pagamentos são feitos de forma segura pela Stripe, uma das plataformas de checkout mais confiáveis e utilizadas no mundo.\n\nApoiar é opcional, mas faz uma enorme diferença para manter o jogo vivo e em constante evolução.\n\nObrigado por jogar",
    shop_info_title: "Informações importantes:",
    shop_info_secure: "• Pagamento rápido e seguro via Stripe\n• Nenhum dado de cartão é armazenado pelo jogo\n• As recompensas são liberadas automaticamente após a confirmação",
    ost_title: "TRILHA SONORA DESBLOQUEADA",
    ost_desc: "A trilha sonora completa do jogo está disponível para download.",
    ost_important_title: "Importante:",
    ost_important_msg: "Os arquivos estão reunidos em um arquivo .ZIP.\nPara acessar as músicas, será necessário usar um aplicativo de descompactação, tanto no celular quanto no computador. Após extrair, você poderá ouvir as faixas livremente.",
    ost_footer: "Boa viagem sonora e obrigado por apoiar um desenvolvedor solo",
    btn_download: "BAIXAR TRILHA SONORA",
    btn_shop: "LOJA / APOIAR",
    gold_reward_title: "RECOMPENSA OBTIDA!",
    gold_reward_msg: "Obrigado pelo seu apoio! As moedas foram adicionadas ao seu jogo.",
    security_intro: "Para proteger sua conta e garantir que a recompensa seja vinculada corretamente ao seu perfil, precisamos de um último passo de segurança.",
    security_step1: "Feche esta janela agora",
    security_step2: "Inicie o jogo novamente pelo bot",
    security_outro: "Assim que o jogo for reaberto, suas moedas já estarão automaticamente adicionadas ao seu perfil.",
    security_thanks: "OBRIGADO PELO SEU APOIO E BOA JORNADA!",
    
    item_sword_1: "Espada Rústica", item_sword_2: "Lâmina Afiada", item_sword_3: "Espada do Veterano", item_sword_4: "Machado Pesado", item_sword_5: "Arma de Guerra",
    item_shield_1: "Escudo de Madeira", item_shield_2: "Escudo Reforçado", item_shield_3: "Placas de Ferro", item_shield_4: "Couraça Pesada", item_shield_5: "Armadura de Batalha",
    item_health_1: "Talismã Vital", item_health_2: "Amuleto de Sangue", item_health_3: "Coração Endurecido", item_health_4: "Relicário Vital", item_health_5: "Essência da Vida",
    item_speed_1: "Botas Leves", item_speed_2: "Passos Ágeis", item_speed_3: "Grevas Rápidas", item_speed_4: "Marca do Vento", item_speed_5: "Reflexos Sobrenaturais",
  },
  EN: {
    // NPCs REWRITTEN
    npc_merchant_wounded_name: "Wounded Merchant", 
    npc_merchant_wounded_desc: "A wounded merchant leans against the wall. His open pack reveals blood-stained coins. He looks up, awaiting your decision.", 
    npc_merchant_wounded_c1: "Give Potion", 
    npc_merchant_wounded_c2: "Give 50 Gold", 
    npc_merchant_wounded_c3: "Ignore", 
    npc_merchant_wounded_c4: "Steal",
    
    npc_prisoner_name: "Catacombs Prisoner", 
    npc_prisoner_desc: "Rusted chains hold an exhausted woman. The ground trembles slightly. You feel your decision will carry weight.", 
    npc_prisoner_c1: "Free", 
    npc_prisoner_c2: "Kill", 
    npc_prisoner_c3: "Ignore",
    
    npc_alchemist_name: "Obsessed Alchemist", 
    npc_alchemist_desc: "Broken vials, toxic fumes, and maddened eyes. He needs an antidote to finish something that perhaps should never exist.", 
    npc_alchemist_c1: "Give Antidote", 
    npc_alchemist_c2: "Refuse", 
    npc_alchemist_c3: "Demand Payment",
    
    npc_idol_name: "Whispering Idol", 
    npc_idol_desc: "The statue pulses faintly. Whispers echo directly in your mind, demanding an offering.", 
    npc_idol_c1: "Offer Gold (100)", 
    npc_idol_c2: "Offer Life (10%)", 
    npc_idol_c3: "Destroy Idol",
    
    npc_knight_name: "Faceless Knight", 
    npc_knight_desc: "A faceless knight holds a broken sword. His voice echoes hollow inside the armor.", 
    npc_knight_c1: "Accept Quest (Kill 3)", 
    npc_knight_c2: "Refuse", 
    npc_knight_c3: "Attack",
    
    npc_child_name: "Lost Child", 
    npc_child_desc: "A scared child cries amidst the shadows. The path ahead is teeming with monsters.", 
    npc_child_c1: "Help (Blessing)", 
    npc_child_c2: "Ignore", 
    npc_child_c3: "Investigate",
    
    npc_cartographer_name: "Old Cartographer", 
    npc_cartographer_desc: "Scribbled maps cover the floor. He sells no items, only inconvenient truths.", 
    npc_cartographer_c1: "Buy Truth (80)", 
    npc_cartographer_c2: "Threaten", 
    npc_cartographer_c3: "Ignore",
    
    npc_voice_name: "Voice in Darkness", 
    npc_voice_desc: "You hear a formless voice. It asks for... something. Maybe attention. Maybe a price.", 
    npc_voice_c1: "Respond", 
    npc_voice_c2: "Offer Gold (50)", 
    npc_voice_c3: "Silence",
    
    npc_guard_name: "Corrupted Guard", 
    npc_guard_desc: "A former protector, now deformed. He asks for redemption with his last shreds of sanity.", 
    npc_guard_c1: "Give Antidote", 
    npc_guard_c2: "Kill", 
    npc_guard_c3: "Ignore",

    // FEEDBACK TITLES & STRINGS
    fb_charity: "Act of Charity",
    fb_greed: "Greed",
    fb_cruelty: "Cruelty",
    fb_ignorance: "Indifference",
    fb_deal: "Deal Struck",
    fb_quest: "Quest Accepted",
    fb_consequence: "Consequence",
    fb_blessing: "Blessing Received",
    fb_curse: "Curse",
    fb_combat: "Imminent Combat",
    fb_theft: "Theft",
    
    fb_desc_merchant_help: "The merchant thanks you with tears. He promises future discounts.",
    fb_desc_merchant_theft: "You steal what you can. The merchant curses your soul.",
    fb_desc_prisoner_free: "She stands up, swearing to fight by your side for a while.",
    fb_desc_alchemist_help: "He laughs maniacally and hands you an unstable mixture.",
    fb_desc_idol_gold: "The idol consumes the gold and glows with power.",
    fb_desc_idol_blood: "The idol drains your blood, but strengthens you.",
    fb_desc_knight_quest: "The knight points his sword at the dark. The hunt begins.",
    fb_desc_child_help: "The child touches your hand. A warm light surrounds you.",
    fb_desc_cartographer: "He reveals the secrets of this floor.",
    fb_desc_voice_response: "The voice whispers ancient secrets.",
    fb_desc_guard_help: "His skin returns to normal. He hands you his shield.",

    // EFFECTS
    eff_merchant_discount: "Merchant Discount (-50%)",
    eff_merchant_tax: "Merchant Tax (+50%)",
    eff_prisoner_join: "Prisoner Ally (10 levels)",
    eff_more_enemies: "More enemies will spawn",
    eff_quest_start: "Defeat 3 Enemies",
    eff_map_reveal: "Map Revealed",
    eff_traps_reveal: "Traps Revealed",

    // ... (Keeping existing translations)
    tut_prove_title: "PROVE YOUR WORTH", tut_prove_desc: "Before advancing, you must prove your worth.\nDefeat at least one enemy to move on.",
    tut_key_title: "FIND THE KEY", tut_key_desc: "The exit is locked.\nExplore the map until you find the key.",
    tut_stairs_title: "USE THE STAIRS", tut_stairs_desc: "With the key in hand, look for the stairs.\nIt leads you to deeper levels.",
    tut_battle_title: "HOW BATTLES WORK", tut_battle_desc: "Battles are automatic.\nYou and the enemy attack in turns.",
    tut_attr_title: "CHARACTER ATTRIBUTES",
    tut_attr_hp: "If health reaches 0, the run ends.",
    tut_attr_atk: "Defines how much damage you deal per turn.",
    tut_attr_def: "Absorbs damage before health. Recovers between battles.",
    tut_attr_spd: "Determines who attacks first.",
    tut_init_title: "INITIATIVE MATTERS", tut_init_desc: "Attacking first can decide the battle.\nSpeed saves lives.",
    tut_merchant_title: "THE MERCHANT", tut_merchant_desc: "You may find a merchant during exploration.\nHe sells direct upgrades to your attributes.",
    tut_choice_title: "CHOICES MATTER", tut_choice_desc: "Not every path is safe.\nNot every decision brings reward.",
    tut_end_title: "THE END", tut_end_desc: "The world doesn't wait for heroes.\nOnly the persistent descend deeper.",

    inventory_title: "INVENTORY", inventory_full_title: "Inventory Full!", inventory_full_btn: "OK", inventory_full: "Inventory full!",
    use: "USAR", store: "STORE", close: "CLOSE", exit: "EXIT", next: "NEXT", start: "START", back: "BACK", yes: "YES", no: "NO", vs: "VS",
    turn_log_title: "Turn Log", save_reset_title: "ABYSS UPDATE", save_reset_desc: "The winds have shifted. Your previous journey was lost in the shadows of an update, but the path opens once more.", save_reset_btn: "ACCEPT FATE",
    descending: "Descending", relic_choice: "CHOOSE A RELIC", relic_active: "ACTIVE RELIC", hero_placeholder: "HERO NAME", continue_journey: "Continue Journey",
    new_game: "New Game", start_journey: "Start Journey", feedback: "Feedback", real_shop: "Shop",
    shop_title: "SUPPORT SHOP", shop_crow_title: "Unlock Crow", shop_crow_desc: "Permanent pet. Detects traps. (Permanent Item)", shop_coffee_title: "Support the Dev",
    shop_coffee_desc: "Buy a coffee for the game creator!", shop_buy_btn: "PURCHASE", unlock_success_title: "REWARD CLAIMED!", unlock_success_desc: "Thank you for your support! The item has been permanently added to your account.",
    level: "Level", hp: "HP", armor: "ARMOR", atk: "ATK", vel: "SPD", diary: "Diary", view_diary: "View Diary", hide_diary: "Hide Diary", death_title: "DEATH", death_desc: "The Abyss claimed your soul.",
    rebirth: "Rebirth", victory: "Victory", collect_reward: "COLLECT REWARD", succumb: "SUCCUMB", chest_title: "Chest Blessing", merchant_title: "Wandering Merchant", altar_title: "Altar of Shadows",
    altar_inactive: "The Altar is silent. Kill an enemy first.", altar_prompt: "Pray at the Altar.", altar_button: "PRAY", close_deal: "Close Deal", bought_pet: "Pet bought!",
    bought_potion: "Potion bought!", bought_item: "Equipped!", tron_active: "GHOST HORSE ACTIVE!", final_stats: "FINAL STATS", blood: "BLOOD", key: "KEY", shop_coins: "COINS", no_effect: "NO EFFECT",
    crow_tooltip: "Watchful Crow", hero_default: "Hero", share_hero: "Hero", share_level: "Level Reached", share_atk: "Attack", share_def: "Shield", share_msg: "Challenge the abyss yourself!", share_copied: "Challenge copied to clipboard!",
    shop_ghost_horse: "Ghost Horse (20s)", shop_ghost_desc: "Max Initiative + Trail", shop_bag: "Expanded Bag (+5 Slots)", shop_bag_desc: "Increases inventory capacity", shop_max: "MAX REACHED", shop_attribute: "Attribute",
    potion_found: "Flask Found", potion_desc: "Recovers", potion_desc_suffix: "% HP", stat_attack: "Attack", stat_armor: "Armor", stat_speed: "Speed",
    log_trampled: "TRAMPLED!", log_explode: "exploded!", log_recover_breath: "You recover your breath...", log_miss: "You missed the attack!", log_anxious: "ANXIOUS STRIKE!", log_crit: "CRITICAL!", log_absorbed: "absorbed",
    log_drain: "drained", log_bleed: "You are bleeding!", log_paralyzed: "PARALYZED! Turn lost!", log_entered: "entered the abyss.", log_descending: "Descending to level", log_key: "Key collected!", log_locked: "Locked! Need key and 1 kill!",
    combat_dealt: "dealt", combat_damage: "damage", combat_player: "You", combat_enemy: "Enemy", combat_pet: "Pet", pet_lobo: "WOLF", pet_puma: "PUMA", pet_corvo: "CROW", pet_cavalo: "HORSE", pet_urso: "BEAR", pet_cachorro: "DOG",
    poisoned: "POISONED", cured: "POISON CURED!", poison_damage: "Poison", trap_spike: "Spike Trap!", trap_poison: "Poison Trap!", trap_alarm: "ALARM! ENEMY ATTRACTED!", trap_explosive: "KABOOM! EXPLOSION!", trap_evaded: "Trap evaded (Speed)!",
    crow_reveal: "Crow revealed traps!",
    level_complete: "LEVEL COMPLETE", next_level_desc: "Darkness embraces you as you descend...", descend_btn: "DESCEND DEEPER",
    
    follower_prisoner: "Prisoner", follower_knight: "Knight", no_potion: "No potions!", no_gold: "No gold!", no_antidote: "No antidote!",
    
    shop_solo_dev_msg: "This game is developed by a solo dev...", shop_info_title: "Important Information:", shop_info_secure: "• Secure payment",
    ost_title: "SOUNDTRACK UNLOCKED", ost_desc: "Download available.", ost_important_title: "Important:", ost_important_msg: "ZIP file.", ost_footer: "Thanks.",
    btn_download: "DOWNLOAD", btn_shop: "SUPPORT", gold_reward_title: "REWARD CLAIMED!", gold_reward_msg: "Coins added.",
    security_intro: "Security step.", security_step1: "Close window", security_step2: "Restart game", security_outro: "Coins added on restart.", security_thanks: "THANKS!",
    
    item_sword_1: "Rustic Sword", item_sword_2: "Sharp Blade", item_sword_3: "Veteran's Sword", item_sword_4: "Heavy Axe", item_sword_5: "War Weapon",
    item_shield_1: "Wooden Shield", item_shield_2: "Reinforced Shield", item_shield_3: "Iron Plates", item_shield_4: "Heavy Plate", item_shield_5: "Battle Armor",
    item_health_1: "Vital Talisman", item_health_2: "Blood Amulet", item_health_3: "Hardened Heart", item_health_4: "Vital Reliquary", item_health_5: "Life Essence",
    item_speed_1: "Light Boots", item_speed_2: "Agile Steps", item_speed_3: "Quick Greaves", item_speed_4: "Wind Mark", item_speed_5: "Supernatural Reflexes",
  },
  ES: {
    // NPCs REWRITTEN
    npc_merchant_wounded_name: "Mercader Herido", 
    npc_merchant_wounded_desc: "Un mercader herido se arrastra contra la pared. Su mochila abierta revela monedas manchadas de sangre. Levanta la vista y espera tu decisión.", 
    npc_merchant_wounded_c1: "Dar Poción", 
    npc_merchant_wounded_c2: "Dar 50 Oro", 
    npc_merchant_wounded_c3: "Ignorar", 
    npc_merchant_wounded_c4: "Robar",
    
    npc_prisoner_name: "Prisionera de las Catacumbas", 
    npc_prisoner_desc: "Cadenas oxidadas sujetan a una mujer exhausta. El suelo tiembla levemente. Sientes que tu decisión tendrá peso.", 
    npc_prisoner_c1: "Liberar", 
    npc_prisoner_c2: "Matar", 
    npc_prisoner_c3: "Ignorar",
    
    npc_alchemist_name: "Alquimista Obsesionado", 
    npc_alchemist_desc: "Frascos rotos, vapores tóxicos y ojos enloquecidos. Necesita un antídoto para concluir algo que tal vez nunca debió existir.", 
    npc_alchemist_c1: "Entregar Antídoto", 
    npc_alchemist_c2: "Rechazar", 
    npc_alchemist_c3: "Exigir Pago",
    
    npc_idol_name: "Ídolo Susurrante", 
    npc_idol_desc: "La estatua pulsa levemente. Susurros resuenan directo en tu mente, exigiendo una ofrenda.", 
    npc_idol_c1: "Ofrecer Oro (100)", 
    npc_idol_c2: "Ofrecer Vida (10%)", 
    npc_idol_c3: "Destruir el Ídolo",
    
    npc_knight_name: "Caballero Sin Rostro", 
    npc_knight_desc: "Un caballero sin rostro sostiene una espada rota. Su voz resuena hueca dentro de la armadura.", 
    npc_knight_c1: "Aceptar Misión (Matar 3)", 
    npc_knight_c2: "Rechazar", 
    npc_knight_c3: "Atacar",
    
    npc_child_name: "Niño Perdido", 
    npc_child_desc: "Un niño asustado llora entre sombras. El camino por delante está repleto de monstruos.", 
    npc_child_c1: "Ayudar (Bendición)", 
    npc_child_c2: "Ignorar", 
    npc_child_c3: "Investigar",
    
    npc_cartographer_name: "Viejo Cartógrafo", 
    npc_cartographer_desc: "Mapas garabateados cubren el suelo. No vende ítems, solo verdades incómodas.", 
    npc_cartographer_c1: "Comprar Verdad (80)", 
    npc_cartographer_c2: "Amenazar", 
    npc_cartographer_c3: "Ignorar",
    
    npc_voice_name: "Voz en la Oscuridad", 
    npc_voice_desc: "Escuchas una voz sin forma. Pide... algo. Tal vez atención. Tal vez un precio.", 
    npc_voice_c1: "Responder", 
    npc_voice_c2: "Ofrecer Oro (50)", 
    npc_voice_c3: "Silencio",
    
    npc_guard_name: "Guardia Corrompido", 
    npc_guard_desc: "Un antiguo protector, ahora deformado. Pide redención con los últimos rasgos de cordura.", 
    npc_guard_c1: "Dar Antídoto", 
    npc_guard_c2: "Matar", 
    npc_guard_c3: "Ignorar",

    // FEEDBACK TITLES & STRINGS
    fb_charity: "Acto de Caridad",
    fb_greed: "Avaricia",
    fb_cruelty: "Crueldad",
    fb_ignorance: "Indiferencia",
    fb_deal: "Trato Hecho",
    fb_quest: "Misión Aceptada",
    fb_consequence: "Consecuencia",
    fb_blessing: "Bendición Recibida",
    fb_curse: "Maldición",
    fb_combat: "Combate Inminente",
    fb_theft: "Robo",
    
    fb_desc_merchant_help: "El mercader agradece con lágrimas. Promete descuentos futuros.",
    fb_desc_merchant_theft: "Robas lo que puedes. El mercader maldice tu alma.",
    fb_desc_prisoner_free: "Ella se levanta, jurando luchar a tu lado por un tiempo.",
    fb_desc_alchemist_help: "Él ríe maniáticamente y te entrega una mezcla inestable.",
    fb_desc_idol_gold: "El ídolo consume el oro y brilla con poder.",
    fb_desc_idol_blood: "El ídolo drena tu sangre, pero te fortalece.",
    fb_desc_knight_quest: "El caballero apunta su espada a la oscuridad. La caza ha comenzado.",
    fb_desc_child_help: "El niño toca tu mano. Una luz cálida te envuelve.",
    fb_desc_cartographer: "Revela los secretos de este piso.",
    fb_desc_voice_response: "La voz susurra secretos antiguos.",
    fb_desc_guard_help: "Su piel vuelve a la normalidad. Te entrega su escudo.",

    // EFFECTS
    eff_merchant_discount: "Descuento Mercader (-50%)",
    eff_merchant_tax: "Impuesto Mercader (+50%)",
    eff_prisoner_join: "Prisionera Aliada (10 niveles)",
    eff_more_enemies: "Más enemigos aparecerán",
    eff_quest_start: "Derrota 3 Enemigos",
    eff_map_reveal: "Mapa Revelado",
    eff_traps_reveal: "Trampas Reveladas",

    // ... (Keeping all existing translations)
    tut_prove_title: "PRUEBA TU VALOR", tut_prove_desc: "Antes de avanzar, debes probar tu valor.\nDerrota al menos a un enemigo para continuar.",
    tut_key_title: "ENCUENTRA LA LLAVE", tut_key_desc: "La salida está cerrada.\nExplora el mapa hasta encontrar la llave.",
    tut_stairs_title: "USA LA ESCALERA", tut_stairs_desc: "Con la llave en mano, busca la escalera.\nTe lleva a niveles más profundos.",
    tut_battle_title: "CÓMO FUNCIONAN LAS BATALLAS", tut_battle_desc: "Las batallas son automáticas.\nTú y el enemigo atacan por turnos.",
    tut_attr_title: "ATRIBUTOS DEL PERSONAJE", 
    tut_attr_hp: "Si la vida llega a 0, la partida termina.",
    tut_attr_atk: "Define cuánto daño causas por turno.",
    tut_attr_def: "Absorbe el daño antes que la vida. Se recupera entre batallas.",
    tut_attr_spd: "Determina quién ataca primero.",
    tut_init_title: "LA INICIATIVA IMPORTA", tut_init_desc: "Atacar primero puede decidir la batalla.\nLa velocidad salva vidas.",
    tut_merchant_title: "EL MERCADER", tut_merchant_desc: "Puedes encontrar un mercader durante la exploración.\nVende mejoras directas para tus atributos.",
    tut_choice_title: "LAS ELECCIONES IMPORTAN", tut_choice_desc: "No todo camino es seguro.\nNo toda decisión trae recompensa.",
    tut_end_title: "EL FIN", tut_end_desc: "El mundo no espera héroes.\nSolo los persistentes descienden más profundo.",

    inventory_title: "INVENTARIO", inventory_full_title: "¡Inventario Lleno!", inventory_full_btn: "OK", inventory_full: "¡Inventario lleno!",
    use: "USAR", store: "GUARDAR", close: "CERRAR", exit: "SALIR", next: "SIGUIENTE", start: "EMPEZAR", back: "VOLVER", yes: "SÍ", no: "NO", vs: "VS",
    turn_log_title: "Registro de Turnos", save_reset_title: "ACTUALIZACIÓN DEL ABISMO", save_reset_desc: "Los vientos han cambiado. Tu viaje anterior se perdió en las sombras de una actualización, pero el camino se abre de nuevo.", save_reset_btn: "ACEPTAR DESTINO",
    descending: "Descendiendo", relic_choice: "ELIGE UNA RELIQUIA", relic_active: "RELIQUIA ACTIVA", hero_placeholder: "NOMBRE DEL HÉROE", continue_journey: "Continuar Viaje",
    new_game: "Nuevo Juego", start_journey: "Iniciar Viaje", feedback: "Feedback", real_shop: "Tienda",
    shop_title: "TIENDA DE APOYO", shop_crow_title: "Desbloquear Cuervo", shop_crow_desc: "Mascota permanente. Detecta trampas. (Item Permanente)", shop_coffee_title: "Apoyar al Dev",
    shop_coffee_desc: "¡Compra un café para quien creó el juego!", shop_buy_btn: "ADQUIRIR", unlock_success_title: "¡RECOMPENSA OBTENIDA!", unlock_success_desc: "¡Gracias por tu apoyo! El item fue añadido permanentemente a tu cuenta.",
    level: "Nivel", hp: "VIDA", armor: "ESCUDO", atk: "ATQ", vel: "VEL", diary: "Diario", view_diary: "Ver Diario", hide_diary: "Ocultar Diario", death_title: "MUERTE", death_desc: "El Abismo reclamó tu alma.",
    rebirth: "Renacer", victory: "Victoria", collect_reward: "RECOGER RECOMPENSA", succumb: "SUCUMBIR AL ABISMO", chest_title: "Bendición del Cofre", merchant_title: "Mercader Errante", altar_title: "Altar de las Sombras",
    altar_inactive: "El Altar permanece en silencio. Mata un enemigo primero.", altar_prompt: "Póstrate ante el Altar y acepta tu destino.", altar_button: "ORAR", close_deal: "Cerrar Trato", bought_pet: "¡Mascota comprada!",
    bought_potion: "¡Poción comprada!", bought_item: "¡Equipado!", tron_active: "¡CABALLO FANTASMA ACTIVADO!", final_stats: "ESTADÍSTICAS FINALES", blood: "SANGRE", key: "LLAVE", shop_coins: "MONEDAS", no_effect: "SIN EFECTO",
    crow_tooltip: "Cuervo Vigilante", hero_default: "Héroe", share_hero: "Héroe", share_level: "Nivel Alcanzado", share_atk: "Ataque", share_def: "Escudo", share_msg: "¡Desafía al abismo tú también!", share_copied: "¡Desafío copiado al portapapeles!",
    shop_ghost_horse: "Caballo Fantasma (20s)", shop_ghost_desc: "Iniciativa Máxima + Rastro", shop_bag: "Mochila Expandida (+5 Slots)", shop_bag_desc: "Aumenta capacidad del inventario", shop_max: "MÁXIMO ALCANZADO", shop_attribute: "Atributo",
    potion_found: "Frasco Encontrado", potion_desc: "Recupera", potion_desc_suffix: "% de vida", stat_attack: "Ataque", stat_armor: "Armadura", stat_speed: "Velocidad",
    log_trampled: "¡ATROPELLADO!", log_explode: "¡explotó!", log_recover_breath: "Recuperas el aliento...", log_miss: "¡Fallaste el ataque!", log_anxious: "¡GOLPE ANSIOSO!", log_crit: "¡CRÍTICO!", log_absorbed: "absorbió",
    log_drain: "drenó", log_bleed: "¡Estás sangrando!", log_paralyzed: "¡PARALIZADO! ¡Perdiste el turno!", log_entered: "entró en el abismo.", log_descending: "Descendiendo al nivel", log_key: "¡Llave recogida!", log_locked: "¡Cerrado. Mata 1 enemigo y toma la llave!",
    combat_dealt: "causó", combat_damage: "de daño", combat_player: "Tú", combat_enemy: "Enemigo", combat_pet: "Mascota", pet_lobo: "LOBO", pet_puma: "PUMA", pet_corvo: "CUERVO", pet_cavalo: "CABALLO", pet_urso: "OSO", pet_cachorro: "PERRO",
    poisoned: "ENVENENADO", cured: "¡CURADO DEL VENENO!", poison_damage: "Veneno", trap_spike: "¡Trampa de Pinchos!", trap_poison: "¡Trampa de Veneno!", trap_alarm: "¡ALARMA! ¡ENEMIGO ATRAÍDO!", trap_explosive: "¡KABOOM! ¡EXPLOSIÓN!", trap_evaded: "¡Trampa evitada (Velocidad)!",
    crow_reveal: "¡El Cuervo avistó trampas!",
    level_complete: "NIVEL COMPLETADO", next_level_desc: "La oscuridad te abraza mientras desciendes...", descend_btn: "DESCENDER MÁS PROFUNDO",

    theme_cave: "Cavernas Profundas", theme_snow: "Picos Congelados", theme_desert: "Dunas Mortales", theme_forest: "Bosque Negro", theme_inferno: "Zona Infernal", theme_ruins: "Ruinas Antiguas",
    theme_void: "Vacío Abisal", theme_mechanical: "Complejo Mecánico", theme_corrupted: "Zona Corrompida", theme_catacombs: "Catacumbas", theme_ossuary: "Osario", theme_astral: "Plano Astral",
    theme_matrix: "Matrix", theme_furnace: "Horno", theme_swamp: "Pantano", theme_temple: "Templo", theme_chaos: "Caos", theme_hive: "Colmena",

    relic_slots_name: "+5 Slot Inventario", relic_slots_desc: "Aumenta permanentemente el inventario en 5 slots.",
    relic_bleed_name: "Diente Serrado", relic_bleed_desc: "+1% de probabilidad de causar sangrado permanente al enemigo.",
    relic_defense_name: "Placa Agrietada", relic_defense_desc: "Reduce en 1 el daño recibido (mínimo 1).",
    relic_crit_name: "Ojo del Cazador", relic_crit_desc: "+1% de probabilidad de crítico.",
    relic_power_name: "Puño Endurecido", relic_power_desc: "Primer ataque en cada piso causa +10% de daño.",
    relic_vamp_name: "Reloj de Arena Carmesí", relic_vamp_desc: "Recupera 15% de vida al matar un enemigo.",
    relic_alch_name: "Residuo Alquímico", relic_alch_desc: "Pociones curan +5% más.",
    relic_save_name: "Frasco Inestable", relic_save_desc: "5% de probabilidad de que una poción no se consuma al usar.",
    relic_memory_name: "Memoria Destilada", relic_memory_desc: "Primera poción usada en cada run tiene efecto doble.",
    relic_gaze_name: "Gasa Antigua", relic_gaze_desc: "Siempre comienza la run con 1 poción que cura +70%.",
    relic_collar_name: "Collar de Huesos", relic_collar_desc: "Mascotas ganan +10 de daño base.",
    relic_bag_name: "Bolsa Cosida", relic_bag_desc: "+5% de oro ganado.",
    relic_coin_name: "Moneda Antigua", relic_coin_desc: "5% de probabilidad de que enemigos suelten oro extra.",
    relic_heart_name: "Corazón Fisurado", relic_heart_desc: "+10% daño, -5% HP máximo.",
    relic_mark_name: "Marca del Sacrificio", relic_mark_desc: "Comienza la run con menos 10% de vida, pero +60 monedas.",
    relic_echo_name: "Eco de las Muertes", relic_echo_desc: "Hereda 20% de todos los atributos de la run anterior.",

    b_sharp_name: "Sangre Afilada", b_sharp_desc: "Tras matar 1 enemigo, +10% de daño hasta salir del nivel.",
    b_fury_name: "Furia Contenida", b_fury_desc: "+15% de daño mientras tengas menos de 50% de vida.",
    b_strike_name: "Golpe Ansioso", b_strike_desc: "El primer ataque en combate causa daño doble.",
    b_fists_name: "Puños Consagrados", b_fists_desc: "Ataques ignoran parte de la defensa enemiga.",
    b_eyes_name: "Ojos Abiertos", b_eyes_desc: "Revela la posición de la llave en el mapa.",
    b_luck_name: "Suerte Peregrina", b_luck_desc: "5% de probabilidad de que cofres den +100 monedas.",
    b_surrendered_name: "Sangre Rendida", b_surrendered_desc: "Recupera 30% de la vida al matar enemigos.",
    b_accepted_name: "Oferta Aceptada", b_accepted_desc: "La primera poción usada no se consume.",
    b_greed_name: "Avaricia Sagrada", b_greed_desc: "Enemigos sueltan +15% de oro en este piso.",
    b_merchant_name: "Bendición del Mercader", b_merchant_desc: "Items cuestan -20% hasta el próximo nivel.",
    b_chest_name: "Cofre Consagrado", b_chest_desc: "El próximo cofre concede bonificación duplicada.",

    c_fragile_name: "Sangre Frágil", c_fragile_desc: "Recibe +10% de daño hasta salir del piso.",
    c_hands_name: "Manos Temblorosas", c_hands_desc: "15% de probabilidad de fallar ataques.",
    c_breath_name: "Aliento Corto", c_breath_desc: "No puedes atacar en turnos consecutivos (recupera aliento).",
    c_mark_name: "Marca de la Presa", c_mark_desc: "Enemigos causan sangrado (-2 HP por turno).",
    c_reflexes_name: "Reflejos Lentos", c_reflexes_desc: "Enemigos atacan primero.",
    c_darkness_name: "Oscuridad Ritual", c_darkness_desc: "Campo de visión reducido.",
    c_thirst_name: "Sed Profana", c_thirst_desc: "Pociones curan -20% menos.",
    c_denied_name: "Oferta Denegada", c_denied_desc: "La primera poción se desperdicia al usar.",
    c_greed_name: "Avaricia Maldita", c_greed_desc: "Enemigos sueltan -25% de oro.",
    c_weight_name: "Peso Muerto", c_weight_desc: "Tu velocidad se reduce.",
    c_tribute_name: "Tributo de Sangre", c_tribute_desc: "Pierdes vida al recoger oro.",

    follower_prisoner: "Prisionera", follower_knight: "Caballero",
    no_potion: "¡Sin pociones!", no_gold: "¡Sin oro!", no_antidote: "¡Sin antídoto!",
    
    shop_solo_dev_msg: "Este juego es desarrollado y mantenido por un desarrollador solitario, con mucho cuidado y dedicación.\nSi te gusta la experiencia y deseas apoyar el proyecto, puedes adquirir cualquiera de los items abajo.\nLas compras ayudan directamente a mantener el juego online, cubrir costos de servidores, herramientas, actualizaciones y nuevas mejoras.\n\nTodos los pagos se realizan de forma segura por Stripe, una de las plataformas de pago más fiables del mundo.\n\nApoyar es opcional, pero hace una gran diferencia para mantener el juego vivo e en constante evolución.\n\nGracias por jugar",
    shop_info_title: "Información importante:",
    shop_info_secure: "• Pago rápido y seguro vía Stripe\n• Ningún dato de tarjeta es almacenado por el juego\n• Las recompensas se liberan automáticamente tras la confirmación",
    ost_title: "BANDA SONORA DESBLOQUEADA",
    ost_desc: "La banda sonora completa del juego está disponible para descarga.",
    ost_important_title: "Importante:",
    ost_important_msg: "Los archivos están reunidos en un archivo .ZIP.\nPara acceder a las canciones, será necesario usar una aplicación de descompresión. Tras extraer, podrás escuchar las pistas libremente.",
    ost_footer: "Buen viaje sonoro y gracias por apoyar a un desarrollador solitario",
    btn_download: "DESCARGAR BANDA SONORA",
    btn_shop: "TIENDA / APOYAR",
    gold_reward_title: "¡RECOMPENSA OBTENIDA!",
    gold_reward_msg: "¡Gracias por tu apoyo! Las monedas han sido añadidas a tu juego.",
    security_intro: "Para proteger tu cuenta y asegurar que la recompensa se vincule correctamente, necesitamos un último paso de seguridad.",
    security_step1: "Cierra esta ventana ahora",
    security_step2: "Inicia el juego nuevamente por el bot",
    security_outro: "Tan pronto como el juego se reabra, tus monedas estarán automáticamente en tu perfil.",
    security_thanks: "¡GRACIAS POR TU APOYO Y BUEN VIAJE!",
    
    item_sword_1: "Espada Rústica", item_sword_2: "Hoja Afilada", item_sword_3: "Espada del Veterano", item_sword_4: "Hacha Pesada", item_sword_5: "Arma de Guerra",
    item_shield_1: "Escudo de Madera", item_shield_2: "Escudo Reforzado", item_shield_3: "Placas de Hierro", item_shield_4: "Coraza Pesada", item_shield_5: "Armadura de Batalla",
    item_health_1: "Talismán Vital", item_health_2: "Amuleto de Sangre", item_health_3: "Corazón Endurecido", item_health_4: "Relicario Vital", item_health_5: "Esencia de Vida",
    item_speed_1: "Botas Ligeras", item_speed_2: "Pasos Ágiles", item_speed_3: "Grevas Rápidas", item_speed_4: "Marca del Vento", item_speed_5: "Reflejos Sobrenaturales",
  }
};
